version: "3.0"

services:
  watchtower:
    image: "containrrr/watchtower"
    command: "--cleanup"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/services/docker/config.json:/config.json"
