version: '3.3'

services:
  traefik:
    image: traefik:2.1.1
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./acme.json:/acme.json"
      - "./traefik-dynamic.toml:/etc/traefik/traefik-dynamic.toml"

networks:
  web:
    external: true
